---
#test
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
 name: helloworld
 namespace: helloworld
 #annotations:
 #  configmanagement.gke.io/cluster-selector: "selector-store-1"
spec:
 strategy:
   type: Recreate
 selector:
   matchLabels:
     app: helloworld
 replicas: 2 # tells deployment to run 1 pods matching the template
 template: # create pods using pod definition in this template
   metadata:
     labels:
       app: helloworld
   spec:
     containers:
     - name: helloworld
       image: us-central1-docker.pkg.dev/us-gcp-ame-con-sjsxu-npd-1/acm-demo-repo/helloworld:v0.1
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: helloworld
 namespace: helloworld
 labels:
   app: helloworld
 #annotations:
 #  configmanagement.gke.io/cluster-selector: "selector-store-1"
spec:
 externalTrafficPolicy: Local
 ports:
 - name: http
   port: 80
   protocol: TCP
   targetPort: 8080
 selector:
   app: helloworld
 type: LoadBalancer