# deployment.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: myapp-deployment
# spec:
#   selector:
#     matchLabels:
#       app: myapp
#   template:
#     metadata:
#       labels:
#         app: myapp
#     spec:
#       containers:
#       - name: myapp-container
#         image: myapp
#         ports:
#         - containerPort: 8080

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: gcr.io/{{ .Values.project_id }}/{{ .Values.app.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
